### PR TITLE
remove redundant references

### PR DESCRIPTION
**Pull request by 4kangjc**

### CODE REVIEW

**Comment by 0x804d8000** [comment]
I just fixed CI. Do you mind rebasing the PR so that the tests can be run?

**Comment by 4kangjc** [comment]
> CI is failing, it seems that the repo won’t build on Ubuntu 22. I’m working on that and will recheck this PR later.

Because of  `catch2` and ` __const__`

**Comment by 0x804d8000** [comment]
Thanks for the fix. Merged. 

As for requirements on compiler or its version, I’m not sure we want to place such constraints. Indeed currently the codebase doesn’t compile in certain environments, however I think it’s better to left this as a TODO instead.

**Comment by 4kangjc** [comment]
> As for requirements on compiler or its version, I’m not sure we want to place such constraints. Indeed currently the codebase doesn’t compile in certain environments, however I think it’s better to left this as a TODO instead.

I see.

**Pull request merged**
